apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: discovery.type
          value: single-node
        image: amazon/opendistro-for-elasticsearch:1.0.2
        name: elasticsearch
        ports:
        - containerPort: 9600
        - containerPort: 9200
        resources:
          requests:
            memory: "1300Mi"
            cpu: "300m"
          limits:
            memory: "1500Mi"
            cpu: "300m"
      restartPolicy: Always
status: {}
